//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendEnterprisingsApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JAFET\\SQLEXPRESS;Initial Catalog=bdEnterprisingApp;Integrated Securit" +
            "y=True;TrustServerCertificate=True")]
        public string bdEnterprisingAppConnectionString {
            get {
                return ((string)(this["bdEnterprisingAppConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Pereira\\SQLEXPRESS09;Initial Catalog=bdEnterprisingApp;Persist Securi" +
            "ty Info=True;User ID=Pereira2002;Password=Pilder1972;Encrypt=True;TrustServerCer" +
            "tificate=True")]
        public string bdEnterprisingAppConnectionString1 {
            get {
                return ((string)(this["bdEnterprisingAppConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JAFET\\SQLEXPRESS;Initial Catalog=bdEnterprisingApp;Integrated Securit" +
            "y=True;Encrypt=True;TrustServerCertificate=True")]
        public string bdEnterprisingAppConnectionString2 {
            get {
                return ((string)(this["bdEnterprisingAppConnectionString2"]));
            }
        }
    }
}
