#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendEnterprisingsApp.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bdEnterprisingApp")]
	public partial class conexionbdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public conexionbdDataContext() : 
				base(global::BackendEnterprisingsApp.Properties.Settings.Default.bdEnterprisingAppConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public conexionbdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionbdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionbdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionbdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_IMAGEN")]
		public int SP_ACTUALIZAR_IMAGEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_IMAGEN", DbType="VarChar(MAX)")] string nOMBRE_IMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RUTA_IMAGEN", DbType="VarChar(MAX)")] string rUTA_IMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, nOMBRE_IMAGEN, rUTA_IMAGEN, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_IMAGEN")]
		public int SP_INSERTAR_IMAGEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_IMAGEN", DbType="VarChar(MAX)")] string nOMBRE_IMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RUTA_IMAGEN", DbType="VarChar(MAX)")] string rUTA_IMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, nOMBRE_IMAGEN, rUTA_IMAGEN, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_REPORTE")]
		public int SP_INSERTAR_REPORTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO_REPORTADO", DbType="Int")] System.Nullable<int> iD_USUARIO_REPORTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION_REPORTE", DbType="VarChar(MAX)")] string dESCRIPCION_REPORTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO_REPORTADO, dESCRIPCION_REPORTE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_REPORTES")]
		public ISingleResult<SP_OBTENER_REPORTESResult> SP_OBTENER_REPORTES()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_REPORTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_IMAGENES_PRODUCTO")]
		public ISingleResult<SP_OBTENER_IMAGENES_PRODUCTOResult> SP_OBTENER_IMAGENES_PRODUCTO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_IMAGENES_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_USUARIO")]
		public int SP_INGRESAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOROL", DbType="Int")] System.Nullable<int> iD_TIPOROL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_USUARIO", DbType="NVarChar(50)")] string nOMBRE_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS_USUARIO", DbType="NVarChar(50)")] string aPELLIDOS_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(100)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(50)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(MAX)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(10)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA_TIEMPO_VERIFICACION", DbType="DateTime")] System.Nullable<System.DateTime> mARCA_TIEMPO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPOROL, nOMBRE_USUARIO, aPELLIDOS_USUARIO, dIRECCION, tELEFONO, cORREO, cONTRASENA, nUMERO_VERIFICACION, mARCA_TIEMPO_VERIFICACION, aCTIVO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(11)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_NUMERO_VERIFICACION_POR_CORREO")]
		public int SP_OBTENER_NUMERO_VERIFICACION_POR_CORREO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="VarChar(6)")] ref string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA_TIEMPO_VERIFICACION", DbType="DateTime")] ref System.Nullable<System.DateTime> mARCA_TIEMPO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUMERO_VERIFICACION, mARCA_TIEMPO_VERIFICACION, eRRORID, eRRORDESCRIPCION);
			nUMERO_VERIFICACION = ((string)(result.GetParameterValue(1)));
			mARCA_TIEMPO_VERIFICACION = ((System.Nullable<System.DateTime>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_USUARIO")]
		public int SP_ACTUALIZAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_NOMBRE", DbType="NVarChar(50)")] string nUEVO_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_APELLIDO", DbType="NVarChar(50)")] string nUEVO_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVA_DIRECCION", DbType="NVarChar(100)")] string nUEVA_DIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_TELEFONO", DbType="NVarChar(50)")] string nUEVO_TELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUEVO_NOMBRE, nUEVO_APELLIDO, nUEVA_DIRECCION, nUEVO_TELEFONO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VALIDAR_CONTRASENA")]
		public int SP_VALIDAR_CONTRASENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(MAX)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cONTRASENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_CONTRASENA_USUARIO")]
		public int SP_ACTUALIZAR_CONTRASENA_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVA_CONTRASENA", DbType="NVarChar(MAX)")] string nUEVA_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUEVA_CONTRASENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO_POR_CORREO")]
		public ISingleResult<SP_OBTENER_USUARIO_POR_CORREOResult> SP_OBTENER_USUARIO_POR_CORREO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_USUARIO", DbType="NVarChar(MAX)")] ref string nOMBRE_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS_USUARIO", DbType="NVarChar(MAX)")] ref string aPELLIDOS_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(MAX)")] ref string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(50)")] ref string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_TIPOROL", DbType="NVarChar(50)")] ref string nOMBRE_TIPOROL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] ref System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nOMBRE_USUARIO, aPELLIDOS_USUARIO, dIRECCION, tELEFONO, nOMBRE_TIPOROL, aCTIVO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			nOMBRE_USUARIO = ((string)(result.GetParameterValue(1)));
			aPELLIDOS_USUARIO = ((string)(result.GetParameterValue(2)));
			dIRECCION = ((string)(result.GetParameterValue(3)));
			tELEFONO = ((string)(result.GetParameterValue(4)));
			nOMBRE_TIPOROL = ((string)(result.GetParameterValue(5)));
			aCTIVO = ((System.Nullable<int>)(result.GetParameterValue(6)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((ISingleResult<SP_OBTENER_USUARIO_POR_CORREOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_ACTIVO_POR_CORREO")]
		public int SP_OBTENER_ACTIVO_POR_CORREO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] ref System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, aCTIVO, eRRORID, eRRORDESCRIPCION);
			aCTIVO = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO_POR_CORREO")]
		public ISingleResult<SP_OBTENER_USUARIO_POR_CORREOResult1> SP_OBTENER_USUARIO_POR_CORREO1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_USUARIO", DbType="NVarChar(MAX)")] ref string nOMBRE_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS_USUARIO", DbType="NVarChar(MAX)")] ref string aPELLIDOS_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(MAX)")] ref string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(50)")] ref string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_TIPOROL", DbType="NVarChar(50)")] ref string nOMBRE_TIPOROL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] ref System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nOMBRE_USUARIO, aPELLIDOS_USUARIO, dIRECCION, tELEFONO, nOMBRE_TIPOROL, aCTIVO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			nOMBRE_USUARIO = ((string)(result.GetParameterValue(1)));
			aPELLIDOS_USUARIO = ((string)(result.GetParameterValue(2)));
			dIRECCION = ((string)(result.GetParameterValue(3)));
			tELEFONO = ((string)(result.GetParameterValue(4)));
			nOMBRE_TIPOROL = ((string)(result.GetParameterValue(5)));
			aCTIVO = ((System.Nullable<int>)(result.GetParameterValue(6)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((ISingleResult<SP_OBTENER_USUARIO_POR_CORREOResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_USUARIO")]
		public int SP_ACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(10)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIEMPO_VERIFICACION", DbType="DateTime")] System.Nullable<System.DateTime> tIEMPO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUMERO_VERIFICACION, tIEMPO_VERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_CODIGO_VERIFICACION")]
		public int SP_ACTUALIZAR_CODIGO_VERIFICACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(10)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA_TIEMPO_VERIFICACION", DbType="DateTime")] System.Nullable<System.DateTime> mARCA_TIEMPO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUMERO_VERIFICACION, mARCA_TIEMPO_VERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_USUARIO")]
		public int SP_ELIMINAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(MAX)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cONTRASENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_BITACORA")]
		public int SP_INSERTAR_BITACORA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASE", DbType="NVarChar(MAX)")] string cLASE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="METODO", DbType="NVarChar(MAX)")] string mETODO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUEST", DbType="NVarChar(MAX)")] string rEQUEST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESPONSE", DbType="NVarChar(MAX)")] string rESPONSE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLASE, mETODO, tIPO, dESCRIPCION, rEQUEST, rESPONSE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_RESENA")]
		public int SP_INGRESAR_RESENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RESENA", DbType="Int")] System.Nullable<int> iD_RESENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VALORACION", DbType="Int")] System.Nullable<int> vALORACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESENA", DbType="VarChar(MAX)")] string rESENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_RESENA, iD_PRODUCTO, iD_USUARIO, vALORACION, rESENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_RESENA")]
		public int SP_ACTUALIZAR_RESENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RESENA", DbType="Int")] System.Nullable<int> iD_RESENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VALORACION", DbType="Int")] System.Nullable<int> vALORACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESENA", DbType="VarChar(MAX)")] string rESENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iD_RESENA, vALORACION, rESENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_RESENA")]
		public int SP_ELIMINAR_RESENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RESENA", DbType="Int")] System.Nullable<int> iD_RESENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_RESENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_RESENA")]
		public ISingleResult<SP_OBTENER_RESENAResult> SP_OBTENER_RESENA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_RESENAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_TIPO_PAGO")]
		public int SP_INGRESAR_TIPO_PAGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PAGO", DbType="NVarChar(MAX)")] string nOMBRE_PAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PAGO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_TIPO_RETIRO")]
		public int SP_INGRESAR_TIPO_RETIRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_RETIRO", DbType="NVarChar(MAX)")] string nOMBRE_RETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_RETIRO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_TIPO_PAGO")]
		public int SP_ELIMINAR_TIPO_PAGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOPAGO", DbType="Int")] System.Nullable<int> iD_TIPOPAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPOPAGO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_TIPO_RETIRO")]
		public int SP_ELIMINAR_TIPO_RETIRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPORETIRO", DbType="Int")] System.Nullable<int> iD_TIPORETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPORETIRO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_TIPO_PAGO")]
		public int SP_ACTUALIZAR_TIPO_PAGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOPAGO", DbType="Int")] System.Nullable<int> iD_TIPOPAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PAGO", DbType="NVarChar(MAX)")] string nOMBRE_PAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPOPAGO, nOMBRE_PAGO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_TIPO_RETIRO")]
		public int SP_ACTUALIZAR_TIPO_RETIRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPORETIRO", DbType="Int")] System.Nullable<int> iD_TIPORETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_RETIRO", DbType="NVarChar(MAX)")] string nOMBRE_RETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPORETIRO, nOMBRE_RETIRO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_TIPO_PAGO")]
		public int SP_ACTIVAR_TIPO_PAGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOPAGO", DbType="Int")] System.Nullable<int> iD_TIPOPAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPOPAGO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_TIPO_RETIRO")]
		public int SP_ACTIVAR_TIPO_RETIRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPORETIRO", DbType="Int")] System.Nullable<int> iD_TIPORETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TIPORETIRO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TIPO_PAGO")]
		public ISingleResult<SP_OBTENER_TIPO_PAGOResult> SP_OBTENER_TIPO_PAGO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_TIPO_PAGOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TIPO_RETIRO")]
		public ISingleResult<SP_OBTENER_TIPO_RETIROResult> SP_OBTENER_TIPO_RETIRO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_TIPO_RETIROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_CATEGORIA")]
		public int SP_ACTIVAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_CATEGORIA")]
		public int SP_ACTUALIZAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_CATEGORIA", DbType="NVarChar(50)")] string nOMBRE_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CATEGORIA, nOMBRE_CATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_CATEGORIA")]
		public int SP_ELIMINAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_PRODUCTO")]
		public int SP_ELIMINAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_CATEGORIA")]
		public int SP_INGRESAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_CATEGORIA", DbType="NVarChar(50)")] string nOMBRE_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_CATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_CATEGORIA")]
		public ISingleResult<SP_OBTENER_CATEGORIAResult> SP_OBTENER_CATEGORIA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_CATEGORIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTO")]
		public ISingleResult<SP_OBTENER_PRODUCTOResult> SP_OBTENER_PRODUCTO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_PRODUCTO")]
		public int SP_ACTIVAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VERIFICAR_CORREO_Y_OBTENER_CONTRASENA")]
		public int SP_VERIFICAR_CORREO_Y_OBTENER_CONTRASENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(MAX)")] ref string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cONTRASENA, eRRORID, eRRORDESCRIPCION);
			cONTRASENA = ((string)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_CONTRASENA_USUARIO_OLVIDADA")]
		public int SP_ACTUALIZAR_CONTRASENA_USUARIO_OLVIDADA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(MAX)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(10)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVA_CONTRASENA", DbType="NVarChar(MAX)")] string nUEVA_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, nUMERO_VERIFICACION, nUEVA_CONTRASENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_ESTADO_PEDIDO")]
		public int SP_ACTUALIZAR_ESTADO_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PEDIDO", DbType="Int")] System.Nullable<int> iD_PEDIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_ESTADO", DbType="Int")] System.Nullable<int> nUEVO_ESTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PEDIDO, nUEVO_ESTADO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_PEDIDO_USUARIO")]
		public int SP_ACTUALIZAR_PEDIDO_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PEDIDO", DbType="Int")] System.Nullable<int> iD_PEDIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOPAGO", DbType="Int")] System.Nullable<int> iD_TIPOPAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPORETIRO", DbType="Int")] System.Nullable<int> iD_TIPORETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTIDAD", DbType="Int")] System.Nullable<int> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACIONES", DbType="VarChar(MAX)")] string oBSERVACIONES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PEDIDO, iD_TIPOPAGO, iD_TIPORETIRO, cANTIDAD, oBSERVACIONES, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_PRODUCTO")]
		public int SP_INGRESAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRENDEDOR", DbType="Int")] System.Nullable<int> iD_EMPRENDEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PRODUCTO", DbType="NVarChar(MAX)")] string nOMBRE_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CATEGORIA, iD_EMPRENDEDOR, nOMBRE_PRODUCTO, dESCRIPCION, aCTIVO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_PEDIDO")]
		public int SP_INGRESAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLIENTE", DbType="Int")] System.Nullable<int> iD_CLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRENDEDOR", DbType="Int")] System.Nullable<int> iD_EMPRENDEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPOPAGO", DbType="Int")] System.Nullable<int> iD_TIPOPAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPORETIRO", DbType="Int")] System.Nullable<int> iD_TIPORETIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTIDAD", DbType="Int")] System.Nullable<int> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACIONES", DbType="VarChar(MAX)")] string oBSERVACIONES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CLIENTE, iD_EMPRENDEDOR, iD_PRODUCTO, iD_TIPOPAGO, iD_TIPORETIRO, cANTIDAD, oBSERVACIONES, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PEDIDOS")]
		public ISingleResult<SP_OBTENER_PEDIDOSResult> SP_OBTENER_PEDIDOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PEDIDOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTO")]
		public ISingleResult<SP_OBTENER_PRODUCTOResult1> SP_OBTENER_PRODUCTO1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PRODUCTOResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HISTORIAL_PEDIDOS")]
		public ISingleResult<SP_OBTENER_HISTORIAL_PEDIDOSResult> SP_OBTENER_HISTORIAL_PEDIDOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_HISTORIAL_PEDIDOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_PEDIDO")]
		public int SP_ELIMINAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PEDIDO", DbType="Int")] System.Nullable<int> iD_PEDIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PEDIDO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTOS_EMPRENDEDOR")]
		public ISingleResult<SP_OBTENER_PRODUCTOS_EMPRENDEDORResult1> SP_OBTENER_PRODUCTOS_EMPRENDEDOR1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRENDEDOR", DbType="Int")] System.Nullable<int> iD_EMPRENDEDOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EMPRENDEDOR);
			return ((ISingleResult<SP_OBTENER_PRODUCTOS_EMPRENDEDORResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDOR")]
		public ISingleResult<SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDORResult> SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRENDEDOR", DbType="Int")] System.Nullable<int> iD_EMPRENDEDOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EMPRENDEDOR);
			return ((ISingleResult<SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PEDIDOS_EMPRENDEDOR")]
		public ISingleResult<SP_OBTENER_PEDIDOS_EMPRENDEDORResult> SP_OBTENER_PEDIDOS_EMPRENDEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRENDEDOR", DbType="Int")] System.Nullable<int> iD_EMPRENDEDOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EMPRENDEDOR);
			return ((ISingleResult<SP_OBTENER_PEDIDOS_EMPRENDEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_PRODUCTO")]
		public int SP_ACTUALIZAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PRODUCTO", DbType="NVarChar(MAX)")] string nOMBRE_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Int")] System.Nullable<int> aCTIVO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iD_CATEGORIA, nOMBRE_PRODUCTO, dESCRIPCION, aCTIVO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_REPORTESResult
	{
		
		private int _ID_REPORTE;
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDOS_USUARIO;
		
		private string _CORREO;
		
		private System.Nullable<System.DateTime> _FECHA_REPORTE;
		
		private string _DESCRIPCION_REPORTE;
		
		public SP_OBTENER_REPORTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_REPORTE", DbType="Int NOT NULL")]
		public int ID_REPORTE
		{
			get
			{
				return this._ID_REPORTE;
			}
			set
			{
				if ((this._ID_REPORTE != value))
				{
					this._ID_REPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(MAX)")]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS_USUARIO", DbType="VarChar(MAX)")]
		public string APELLIDOS_USUARIO
		{
			get
			{
				return this._APELLIDOS_USUARIO;
			}
			set
			{
				if ((this._APELLIDOS_USUARIO != value))
				{
					this._APELLIDOS_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(MAX)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REPORTE", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_REPORTE
		{
			get
			{
				return this._FECHA_REPORTE;
			}
			set
			{
				if ((this._FECHA_REPORTE != value))
				{
					this._FECHA_REPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_REPORTE", DbType="VarChar(MAX)")]
		public string DESCRIPCION_REPORTE
		{
			get
			{
				return this._DESCRIPCION_REPORTE;
			}
			set
			{
				if ((this._DESCRIPCION_REPORTE != value))
				{
					this._DESCRIPCION_REPORTE = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_IMAGENES_PRODUCTOResult
	{
		
		private int _ID_IMAGEN;
		
		private System.Nullable<int> _ID_PRODUCTO;
		
		private string _NOMBRE_IMAGEN;
		
		private string _RUTA_IMAGEN;
		
		public SP_OBTENER_IMAGENES_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_IMAGEN", DbType="Int NOT NULL")]
		public int ID_IMAGEN
		{
			get
			{
				return this._ID_IMAGEN;
			}
			set
			{
				if ((this._ID_IMAGEN != value))
				{
					this._ID_IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int")]
		public System.Nullable<int> ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_IMAGEN", DbType="VarChar(MAX)")]
		public string NOMBRE_IMAGEN
		{
			get
			{
				return this._NOMBRE_IMAGEN;
			}
			set
			{
				if ((this._NOMBRE_IMAGEN != value))
				{
					this._NOMBRE_IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTA_IMAGEN", DbType="VarChar(MAX)")]
		public string RUTA_IMAGEN
		{
			get
			{
				return this._RUTA_IMAGEN;
			}
			set
			{
				if ((this._RUTA_IMAGEN != value))
				{
					this._RUTA_IMAGEN = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIO_POR_CORREOResult
	{
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDOS_USUARIO;
		
		private string _DIRECCION;
		
		private System.Nullable<int> _TELEFONO;
		
		private string _CORREO;
		
		private string _NOMBRE_TIPOROL;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_USUARIO_POR_CORREOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(MAX)")]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS_USUARIO", DbType="VarChar(MAX)")]
		public string APELLIDOS_USUARIO
		{
			get
			{
				return this._APELLIDOS_USUARIO;
			}
			set
			{
				if ((this._APELLIDOS_USUARIO != value))
				{
					this._APELLIDOS_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(MAX)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Int")]
		public System.Nullable<int> TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(MAX)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPOROL", DbType="VarChar(50)")]
		public string NOMBRE_TIPOROL
		{
			get
			{
				return this._NOMBRE_TIPOROL;
			}
			set
			{
				if ((this._NOMBRE_TIPOROL != value))
				{
					this._NOMBRE_TIPOROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIO_POR_CORREOResult1
	{
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDOS_USUARIO;
		
		private string _DIRECCION;
		
		private System.Nullable<int> _TELEFONO;
		
		private string _CORREO;
		
		private string _NOMBRE_TIPOROL;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_USUARIO_POR_CORREOResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(MAX)")]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS_USUARIO", DbType="VarChar(MAX)")]
		public string APELLIDOS_USUARIO
		{
			get
			{
				return this._APELLIDOS_USUARIO;
			}
			set
			{
				if ((this._APELLIDOS_USUARIO != value))
				{
					this._APELLIDOS_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(MAX)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Int")]
		public System.Nullable<int> TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(MAX)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPOROL", DbType="VarChar(50)")]
		public string NOMBRE_TIPOROL
		{
			get
			{
				return this._NOMBRE_TIPOROL;
			}
			set
			{
				if ((this._NOMBRE_TIPOROL != value))
				{
					this._NOMBRE_TIPOROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_RESENAResult
	{
		
		private int _ID_RESENA;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _DESCRIPCION;
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDOS_USUARIO;
		
		private System.Nullable<int> _TELEFONO;
		
		private System.Nullable<int> _VALORACION;
		
		private string _RESENA;
		
		public SP_OBTENER_RESENAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RESENA", DbType="Int NOT NULL")]
		public int ID_RESENA
		{
			get
			{
				return this._ID_RESENA;
			}
			set
			{
				if ((this._ID_RESENA != value))
				{
					this._ID_RESENA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(MAX)")]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS_USUARIO", DbType="VarChar(MAX)")]
		public string APELLIDOS_USUARIO
		{
			get
			{
				return this._APELLIDOS_USUARIO;
			}
			set
			{
				if ((this._APELLIDOS_USUARIO != value))
				{
					this._APELLIDOS_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Int")]
		public System.Nullable<int> TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORACION", DbType="Int")]
		public System.Nullable<int> VALORACION
		{
			get
			{
				return this._VALORACION;
			}
			set
			{
				if ((this._VALORACION != value))
				{
					this._VALORACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESENA", DbType="VarChar(MAX)")]
		public string RESENA
		{
			get
			{
				return this._RESENA;
			}
			set
			{
				if ((this._RESENA != value))
				{
					this._RESENA = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TIPO_PAGOResult
	{
		
		private int _ID_TIPOPAGO;
		
		private string _NOMBRE_PAGO;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_TIPO_PAGOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPOPAGO", DbType="Int NOT NULL")]
		public int ID_TIPOPAGO
		{
			get
			{
				return this._ID_TIPOPAGO;
			}
			set
			{
				if ((this._ID_TIPOPAGO != value))
				{
					this._ID_TIPOPAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAGO", DbType="VarChar(50)")]
		public string NOMBRE_PAGO
		{
			get
			{
				return this._NOMBRE_PAGO;
			}
			set
			{
				if ((this._NOMBRE_PAGO != value))
				{
					this._NOMBRE_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TIPO_RETIROResult
	{
		
		private int _ID_TIPORETIRO;
		
		private string _NOMBRE_RETIRO;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_TIPO_RETIROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPORETIRO", DbType="Int NOT NULL")]
		public int ID_TIPORETIRO
		{
			get
			{
				return this._ID_TIPORETIRO;
			}
			set
			{
				if ((this._ID_TIPORETIRO != value))
				{
					this._ID_TIPORETIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RETIRO", DbType="VarChar(50)")]
		public string NOMBRE_RETIRO
		{
			get
			{
				return this._NOMBRE_RETIRO;
			}
			set
			{
				if ((this._NOMBRE_RETIRO != value))
				{
					this._NOMBRE_RETIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_CATEGORIAResult
	{
		
		private int _ID_CATEGORIA;
		
		private string _NOMBRE_CATEGORIA;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_CATEGORIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int NOT NULL")]
		public int ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CATEGORIA", DbType="VarChar(50)")]
		public string NOMBRE_CATEGORIA
		{
			get
			{
				return this._NOMBRE_CATEGORIA;
			}
			set
			{
				if ((this._NOMBRE_CATEGORIA != value))
				{
					this._NOMBRE_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOResult
	{
		
		private int _ID_PRODUCTO;
		
		private System.Nullable<int> _ID_CATEGORIA;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _DESCRIPCION;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int")]
		public System.Nullable<int> ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PEDIDOSResult
	{
		
		private int _ID_PEDIDO;
		
		private string _NOMBRE_CLIENTE;
		
		private string _APELLIDOS_CLIENTE;
		
		private System.Nullable<int> _TELEFONO;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _NOMBRE_PAGO;
		
		private string _NOMBRE_RETIRO;
		
		private System.Nullable<System.DateTime> _FECHA_PEDIDO;
		
		private System.Nullable<int> _CANTIDAD;
		
		private string _OBSERVACIONES;
		
		private System.Nullable<int> _ESTADO;
		
		public SP_OBTENER_PEDIDOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NOMBRE CLIENTE]", Storage="_NOMBRE_CLIENTE", DbType="VarChar(MAX)")]
		public string NOMBRE_CLIENTE
		{
			get
			{
				return this._NOMBRE_CLIENTE;
			}
			set
			{
				if ((this._NOMBRE_CLIENTE != value))
				{
					this._NOMBRE_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[APELLIDOS CLIENTE]", Storage="_APELLIDOS_CLIENTE", DbType="VarChar(MAX)")]
		public string APELLIDOS_CLIENTE
		{
			get
			{
				return this._APELLIDOS_CLIENTE;
			}
			set
			{
				if ((this._APELLIDOS_CLIENTE != value))
				{
					this._APELLIDOS_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Int")]
		public System.Nullable<int> TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAGO", DbType="VarChar(50)")]
		public string NOMBRE_PAGO
		{
			get
			{
				return this._NOMBRE_PAGO;
			}
			set
			{
				if ((this._NOMBRE_PAGO != value))
				{
					this._NOMBRE_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RETIRO", DbType="VarChar(50)")]
		public string NOMBRE_RETIRO
		{
			get
			{
				return this._NOMBRE_RETIRO;
			}
			set
			{
				if ((this._NOMBRE_RETIRO != value))
				{
					this._NOMBRE_RETIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PEDIDO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_PEDIDO
		{
			get
			{
				return this._FECHA_PEDIDO;
			}
			set
			{
				if ((this._FECHA_PEDIDO != value))
				{
					this._FECHA_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int")]
		public System.Nullable<int> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(MAX)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOResult1
	{
		
		private int _ID_PRODUCTO;
		
		private System.Nullable<int> _ID_CATEGORIA;
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDOS_USUARIO;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _DESCRIPCION;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_PRODUCTOResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int")]
		public System.Nullable<int> ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(MAX)")]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS_USUARIO", DbType="VarChar(MAX)")]
		public string APELLIDOS_USUARIO
		{
			get
			{
				return this._APELLIDOS_USUARIO;
			}
			set
			{
				if ((this._APELLIDOS_USUARIO != value))
				{
					this._APELLIDOS_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HISTORIAL_PEDIDOSResult
	{
		
		private int _ID_HISTORIAL;
		
		private int _ID_PEDIDO;
		
		private string _NOMBRE_PRODUCTO;
		
		private System.Nullable<int> _ESTADO_PEDIDO;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZACION;
		
		public SP_OBTENER_HISTORIAL_PEDIDOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL", DbType="Int NOT NULL")]
		public int ID_HISTORIAL
		{
			get
			{
				return this._ID_HISTORIAL;
			}
			set
			{
				if ((this._ID_HISTORIAL != value))
				{
					this._ID_HISTORIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_PEDIDO", DbType="Int")]
		public System.Nullable<int> ESTADO_PEDIDO
		{
			get
			{
				return this._ESTADO_PEDIDO;
			}
			set
			{
				if ((this._ESTADO_PEDIDO != value))
				{
					this._ESTADO_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FECHA ACTUALIZACION]", Storage="_FECHA_ACTUALIZACION", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZACION
		{
			get
			{
				return this._FECHA_ACTUALIZACION;
			}
			set
			{
				if ((this._FECHA_ACTUALIZACION != value))
				{
					this._FECHA_ACTUALIZACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOS_EMPRENDEDORResult1
	{
		
		private int _ID_PRODUCTO;
		
		private System.Nullable<int> _ID_CATEGORIA;
		
		private System.Nullable<int> _ID_EMPRENDEDOR;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _DESCRIPCION;
		
		private System.Nullable<int> _ACTIVO;
		
		public SP_OBTENER_PRODUCTOS_EMPRENDEDORResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int")]
		public System.Nullable<int> ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRENDEDOR", DbType="Int")]
		public System.Nullable<int> ID_EMPRENDEDOR
		{
			get
			{
				return this._ID_EMPRENDEDOR;
			}
			set
			{
				if ((this._ID_EMPRENDEDOR != value))
				{
					this._ID_EMPRENDEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Int")]
		public System.Nullable<int> ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDORResult
	{
		
		private int _ID_HISTORIAL;
		
		private int _ID_PEDIDO;
		
		private int _ID_USUARIO;
		
		private string _NOMBRE_PRODUCTO;
		
		private System.Nullable<int> _ESTADO_PEDIDO;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZACION;
		
		public SP_OBTENER_HISTORIAL_PEDIDOS_EMPRENDEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL", DbType="Int NOT NULL")]
		public int ID_HISTORIAL
		{
			get
			{
				return this._ID_HISTORIAL;
			}
			set
			{
				if ((this._ID_HISTORIAL != value))
				{
					this._ID_HISTORIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_PEDIDO", DbType="Int")]
		public System.Nullable<int> ESTADO_PEDIDO
		{
			get
			{
				return this._ESTADO_PEDIDO;
			}
			set
			{
				if ((this._ESTADO_PEDIDO != value))
				{
					this._ESTADO_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FECHA ACTUALIZACION]", Storage="_FECHA_ACTUALIZACION", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZACION
		{
			get
			{
				return this._FECHA_ACTUALIZACION;
			}
			set
			{
				if ((this._FECHA_ACTUALIZACION != value))
				{
					this._FECHA_ACTUALIZACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PEDIDOS_EMPRENDEDORResult
	{
		
		private int _ID_PEDIDO;
		
		private string _NOMBRE_CLIENTE;
		
		private string _APELLIDOS_CLIENTE;
		
		private System.Nullable<int> _TELEFONO;
		
		private string _NOMBRE_PRODUCTO;
		
		private string _NOMBRE_PAGO;
		
		private string _NOMBRE_RETIRO;
		
		private System.Nullable<System.DateTime> _FECHA_PEDIDO;
		
		private System.Nullable<int> _CANTIDAD;
		
		private string _OBSERVACIONES;
		
		private System.Nullable<int> _ESTADO;
		
		public SP_OBTENER_PEDIDOS_EMPRENDEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NOMBRE CLIENTE]", Storage="_NOMBRE_CLIENTE", DbType="VarChar(MAX)")]
		public string NOMBRE_CLIENTE
		{
			get
			{
				return this._NOMBRE_CLIENTE;
			}
			set
			{
				if ((this._NOMBRE_CLIENTE != value))
				{
					this._NOMBRE_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[APELLIDOS CLIENTE]", Storage="_APELLIDOS_CLIENTE", DbType="VarChar(MAX)")]
		public string APELLIDOS_CLIENTE
		{
			get
			{
				return this._APELLIDOS_CLIENTE;
			}
			set
			{
				if ((this._APELLIDOS_CLIENTE != value))
				{
					this._APELLIDOS_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Int")]
		public System.Nullable<int> TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="VarChar(MAX)")]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAGO", DbType="VarChar(50)")]
		public string NOMBRE_PAGO
		{
			get
			{
				return this._NOMBRE_PAGO;
			}
			set
			{
				if ((this._NOMBRE_PAGO != value))
				{
					this._NOMBRE_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RETIRO", DbType="VarChar(50)")]
		public string NOMBRE_RETIRO
		{
			get
			{
				return this._NOMBRE_RETIRO;
			}
			set
			{
				if ((this._NOMBRE_RETIRO != value))
				{
					this._NOMBRE_RETIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PEDIDO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_PEDIDO
		{
			get
			{
				return this._FECHA_PEDIDO;
			}
			set
			{
				if ((this._FECHA_PEDIDO != value))
				{
					this._FECHA_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int")]
		public System.Nullable<int> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(MAX)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
